### PR TITLE
Fix/adjust argument order validate versions#1

### PR DESCRIPTION
**Pull request by RobinGranstromKall**
Fixing #1

Had to reorder the arguments to allow optional `new_version`

### CODE REVIEW

**Comment by alirezatheh** [comment]
Nice! Thanks a lot 🥂.
I've updated v1 tag contain new changes. 🎉

**Comment by RobinGranstromKall** [comment]
I have just realised that my fix was not enough.
The next script (`bump_changelog `) will require `new-versions`.

I will tinker on a solution and propose it to you. Perhaps setting the output earlier..

**Comment by alirezatheh** [comment]
To solve this you just need to set a `None` default value for `new_version` in that script too.

**Comment by alirezatheh** [comment]
It is fixed now.

**Pull request merged**
